name: Build Arch Package

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '0 2 * * *'
#  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo fontconfig github-cli

      - name: Get upstream commit hash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO="google/fonts"
          BRANCH="main"
          
          # Get short hash using gh CLI
          SHORT_HASH=$(gh api "repos/$REPO/commits/$BRANCH" --jq '.sha[0:9]')
          
          echo "FONTS_HASH=$SHORT_HASH" >> $GITHUB_OUTPUT

          echo $FONTS_HASH
          echo $SHORT_HASH

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone AUR package
        run: su - builder -c "git clone https://aur.archlinux.org/ttf-google-fonts-git.git"

      - name: Build package
        env:
          PACKAGER: Sergey Kanafyev <${{ github.event.pusher.email }}>
          #COMPRESSZST: '(zstd -c -T0 --ultra -20 -)'
        run: su - builder -c "cd ttf-google-fonts-git && makepkg --nodeps --noconfirm"

      - name: Copy package to workspace
        run: cp --verbose /home/builder/ttf-google-fonts-git/*.pkg.tar.zst .

      - name: Create apk release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $FONTS_HASH *.pkg.tar.zst --repo ${{ github.repository }}
